const business = { inquiryEmail: 'bookings@your-namecheap-domain.com' };
const products = [
  { name: 'Golden Hour', family: 'Amber · citrus · woods', status: 'Available now', action: 'Reserve bottle', color: '#d9b16e', cap: '#3e3021', label: 'GOLDEN\nHOUR', stock: 'in-stock' },
  { name: 'Velvet Fig', family: 'Fig · iris · sandalwood', status: 'Source on request', action: 'Request sourcing', color: '#b29a86', cap: '#4a3d37', label: 'VELVET\nFIG', stock: 'request' },
  { name: 'After Dark', family: 'Rose · incense · leather', status: 'Available now', action: 'Reserve bottle', color: '#7b3c3d', cap: '#1f2520', label: 'AFTER\nDARK', stock: 'in-stock' },
  { name: 'Linen Skin', family: 'Musk · neroli · clean woods', status: 'Source on request', action: 'Request sourcing', color: '#c6d2c0', cap: '#526158', label: 'LINEN\nSKIN', stock: 'request' },
  { name: 'Cedar Room', family: 'Cedar · saffron · amber', status: 'Available now', action: 'Reserve bottle', color: '#aa7452', cap: '#302a23', label: 'CEDAR\nROOM', stock: 'in-stock' },
  { name: 'Quiet Bloom', family: 'Peony · tea · white musk', status: 'Source on request', action: 'Request sourcing', color: '#c996a4', cap: '#563c48', label: 'QUIET\nBLOOM', stock: 'request' }
];
const grid = document.querySelector('#product-grid');
const count = document.querySelector('#inquiry-count');
let inquiryItems = [];
function render(filter = 'all') {
  grid.innerHTML = products.filter(p => filter === 'all' || p.stock === filter).map((p, index) => `<article class="product-card" style="--card:${p.color}"><div class="mist"></div><div class="bottle" style="background:linear-gradient(120deg,rgba(255,245,220,.6),${p.color} 55%,rgba(28,25,20,.82));"><div class="bottle-cap" style="background:${p.cap}"></div><div class="bottle-label">${p.label.replace('\n','<br />')}</div></div><button data-item="${index}" aria-label="${p.action}: ${p.name}">+</button><div class="product-meta"><p>${p.family}</p><h3>${p.name}</h3><div><span class="status">${p.status}</span><span>${p.action} ↗</span></div></div></article>`).join('');
}
render();
document.querySelectorAll('[data-filter]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach(b => b.classList.remove('active')); button.classList.add('active'); render(button.dataset.filter); }));
const dialog = document.querySelector('#inquiry-dialog');
document.querySelectorAll('[data-open-inquiry]').forEach(button => button.addEventListener('click', () => dialog.showModal()));
document.querySelectorAll('[data-close-inquiry]').forEach(button => button.addEventListener('click', () => dialog.close()));
grid.addEventListener('click', event => { const button = event.target.closest('[data-item]'); if (!button) return; const product = products[button.dataset.item]; inquiryItems.push(product.name); count.textContent = inquiryItems.length; document.querySelector('[name="request"]').value = `${product.name} — ${product.action}. Please confirm the current bottle size, authenticity documentation, landed price, and availability.`; dialog.showModal(); });
let mood = '', moment = '';
document.querySelectorAll('[data-mood]').forEach(button => button.addEventListener('click', () => { mood = button.dataset.mood; document.querySelectorAll('[data-mood]').forEach(b => b.classList.remove('active')); button.classList.add('active'); }));
document.querySelectorAll('[data-moment]').forEach(button => button.addEventListener('click', () => { moment = button.dataset.moment; document.querySelectorAll('[data-moment]').forEach(b => b.classList.remove('active')); button.classList.add('active'); }));
const directions = { soft:['01','Musk, neroli, and clean woods','Start with a skin-close scent: clean musk, soft citrus, or tea notes. Ask us for bottles that feel present only when someone comes close.'], bright:['02','Citrus, fruit, and radiant florals','Look for sparkling citrus, pear, orange blossom, or a bright floral opening. These are scents that arrive before you do.'], warm:['03','Amber, vanilla, and sandalwood','Choose a warm architecture: amber, saffron, vanilla, tonka, and woods. The result is generous, lasting, and intimate.'], dark:['04','Incense, leather, and deep rose','Move toward incense, dark rose, patchouli, leather, or resin. This direction is composed, textured, and quietly dramatic.'] };
document.querySelector('#reveal-scent').addEventListener('click', () => { const result = document.querySelector('#scent-result'); if (!mood || !moment) { result.innerHTML = '<span class="result-number">?</span><h3>Choose both prompts.</h3><p>Your mood and moment help us make a useful, personal starting point.</p>'; return; } const [number,title,copy] = directions[mood]; result.innerHTML = `<span class="result-number">${number} / ${moment}</span><h3>${title}</h3><p>${copy}</p>`; });
document.querySelector('#inquiry-form').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent('The Source inquiry'); const body = encodeURIComponent(`Name: ${data.get('name')}\nContact: ${data.get('contact')}\n\nRequest:\n${data.get('request')}`); const status = document.querySelector('#form-status'); if (business.inquiryEmail.includes('your-namecheap-domain')) { status.textContent = 'The inquiry email has not been configured yet. Your request is ready; add the Namecheap mailbox to script.js before launch.'; return; } window.location.href = `mailto:${business.inquiryEmail}?subject=${subject}&body=${body}`; status.textContent = 'Your email application is opening with the inquiry prepared.'; });
